-- Demo catalog data migration (OPTIONAL deploy via db push).
-- Inserts only public catalog tables — no auth/users/orders.
-- Idempotent. Prefer local seed via `supabase db reset` during development.
-- Generated by scripts/generate_catalog_seed.py

-- Catalog seed data for Badminton Store
-- Generated by scripts/generate_catalog_seed.py — do not hand-edit.
-- Scope: categories, brands, products, product_variants,
--        product_images, inventory only.
-- Idempotent via ON CONFLICT. Deterministic UUID ranges:
--   categories 10000000-..., brands 20000000-...,
--   products 30000000-..., variants 40000000-..., images 50000000-...

begin;

-- ========== categories ==========
insert into public.categories (id, parent_id, name, slug, description, image_path, sort_order, is_active)
values
  ('10000000-0000-4000-8000-000000000001', null, 'Vợt cầu lông', 'vot-cau-long', 'Vợt thi đấu và luyện tập cho mọi trình độ', 'category-assets/10000000-0000-4000-8000-000000000001/main.webp', 10, true),
  ('10000000-0000-4000-8000-000000000002', null, 'Giày cầu lông', 'giay-cau-long', 'Giày chuyên dụng sân trong nhà', 'category-assets/10000000-0000-4000-8000-000000000002/main.webp', 20, true),
  ('10000000-0000-4000-8000-000000000003', null, 'Cầu lông', 'cau-long', 'Cầu lông ống thi đấu và luyện tập', 'category-assets/10000000-0000-4000-8000-000000000003/main.webp', 30, true),
  ('10000000-0000-4000-8000-000000000004', null, 'Cước đan vợt', 'cuoc-dan-vot', 'Dây đan vợt cảm giác và độ bền', 'category-assets/10000000-0000-4000-8000-000000000004/main.webp', 40, true),
  ('10000000-0000-4000-8000-000000000005', null, 'Quấn cán', 'quan-can', 'Grip và overgrip chống trượt', 'category-assets/10000000-0000-4000-8000-000000000005/main.webp', 50, true),
  ('10000000-0000-4000-8000-000000000006', null, 'Túi và balo cầu lông', 'tui-balo-cau-long', 'Túi vợt và balo đựng phụ kiện', 'category-assets/10000000-0000-4000-8000-000000000006/main.webp', 60, true),
  ('10000000-0000-4000-8000-000000000007', null, 'Quần áo cầu lông', 'quan-ao-cau-long', 'Áo quần thi đấu và tập luyện', 'category-assets/10000000-0000-4000-8000-000000000007/main.webp', 70, true),
  ('10000000-0000-4000-8000-000000000008', null, 'Vớ thể thao', 'vo-the-thao', 'Vớ đệm êm cho sân cầu lông', 'category-assets/10000000-0000-4000-8000-000000000008/main.webp', 80, true),
  ('10000000-0000-4000-8000-000000000009', null, 'Đồ bảo hộ', 'do-bao-ho', 'Băng hỗ trợ cổ tay, gối, mắt cá', 'category-assets/10000000-0000-4000-8000-000000000009/main.webp', 90, true),
  ('10000000-0000-4000-8000-000000000010', null, 'Phụ kiện tập luyện', 'phu-kien-tap-luyen', 'Dụng cụ rèn chân và thể lực', 'category-assets/10000000-0000-4000-8000-000000000010/main.webp', 100, true)
on conflict (id) do update set
  name = excluded.name,
  slug = excluded.slug,
  description = excluded.description,
  image_path = excluded.image_path,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  updated_at = timezone('utc', now());

-- ========== brands ==========
insert into public.brands (id, name, slug, description, logo_path, country_of_origin, sort_order, is_active)
values
  ('20000000-0000-4000-8000-000000000001', 'Yonex', 'yonex', 'Thương hiệu tham chiếu trong dữ liệu demo', 'brand-assets/20000000-0000-4000-8000-000000000001/logo.webp', 'Japan', 10, true),
  ('20000000-0000-4000-8000-000000000002', 'Victor', 'victor', 'Thương hiệu tham chiếu trong dữ liệu demo', 'brand-assets/20000000-0000-4000-8000-000000000002/logo.webp', 'Taiwan', 20, true),
  ('20000000-0000-4000-8000-000000000003', 'Li-Ning', 'li-ning', 'Thương hiệu tham chiếu trong dữ liệu demo', 'brand-assets/20000000-0000-4000-8000-000000000003/logo.webp', 'China', 30, true),
  ('20000000-0000-4000-8000-000000000004', 'Mizuno', 'mizuno', 'Thương hiệu tham chiếu trong dữ liệu demo', 'brand-assets/20000000-0000-4000-8000-000000000004/logo.webp', 'Japan', 40, true),
  ('20000000-0000-4000-8000-000000000005', 'Kumpoo', 'kumpoo', 'Thương hiệu tham chiếu trong dữ liệu demo', 'brand-assets/20000000-0000-4000-8000-000000000005/logo.webp', 'China', 50, true),
  ('20000000-0000-4000-8000-000000000006', 'Apacs', 'apacs', 'Thương hiệu tham chiếu trong dữ liệu demo', 'brand-assets/20000000-0000-4000-8000-000000000006/logo.webp', 'Malaysia', 60, true),
  ('20000000-0000-4000-8000-000000000007', 'Kamito', 'kamito', 'Thương hiệu tham chiếu trong dữ liệu demo', 'brand-assets/20000000-0000-4000-8000-000000000007/logo.webp', 'Vietnam', 70, true),
  ('20000000-0000-4000-8000-000000000008', 'ProAce', 'proace', 'Thương hiệu tham chiếu trong dữ liệu demo', 'brand-assets/20000000-0000-4000-8000-000000000008/logo.webp', 'Vietnam', 80, true)
on conflict (id) do update set
  name = excluded.name,
  slug = excluded.slug,
  description = excluded.description,
  logo_path = excluded.logo_path,
  country_of_origin = excluded.country_of_origin,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  updated_at = timezone('utc', now());

-- ========== products ==========
insert into public.products (
  id, category_id, brand_id, name, slug, short_description, description,
  specifications, search_keywords, status, is_featured, published_at
)
values
  ('30000000-0000-4000-8000-000000000001', '10000000-0000-4000-8000-000000000001', '20000000-0000-4000-8000-000000000001', 'Vợt cầu lông Yonex Aero Strike 88', 'vot-yonex-aero-strike-88', 'Vợt cân bằng tốc độ dành cho trình độ trung cấp', 'Sản phẩm demo minh họa vợt cân bằng. Không phải bản thương mại chính thức.', '{"material": "High Modulus Graphite", "balance": "Even", "shaft_stiffness": "Medium", "recommended_tension_lbs": "20-28", "player_level": "Intermediate", "play_style": "All-round"}'::jsonb, 'vot yonex aero strike 88', 'active', true, '2026-06-01T00:00:00Z'),
  ('30000000-0000-4000-8000-000000000002', '10000000-0000-4000-8000-000000000001', '20000000-0000-4000-8000-000000000002', 'Vợt cầu lông Victor Power Core X7', 'vot-victor-power-core-x7', 'Vợt thiên công lực đập mạnh', 'Sản phẩm demo minh họa vợt head-heavy cho lối đánh tấn công.', '{"material": "Graphite Composite", "balance": "Head Heavy", "shaft_stiffness": "Stiff", "recommended_tension_lbs": "24-30", "player_level": "Advanced", "play_style": "Attack"}'::jsonb, 'vot victor power core x7', 'active', true, '2026-06-02T00:00:00Z'),
  ('30000000-0000-4000-8000-000000000003', '10000000-0000-4000-8000-000000000001', '20000000-0000-4000-8000-000000000003', 'Vợt cầu lông Li-Ning Wind Blade 900', 'vot-li-ning-wind-blade-900', 'Vợt nhẹ tối ưu tốc độ phản xạ', 'Sản phẩm demo minh họa vợt nhẹ cho lối đánh nhanh.', '{"material": "Carbon Fiber", "balance": "Head Light", "shaft_stiffness": "Flexible", "recommended_tension_lbs": "20-26", "player_level": "Intermediate", "play_style": "Speed"}'::jsonb, 'vot li-ning wind blade 900', 'active', true, '2026-06-03T00:00:00Z'),
  ('30000000-0000-4000-8000-000000000004', '10000000-0000-4000-8000-000000000001', '20000000-0000-4000-8000-000000000004', 'Vợt cầu lông Mizuno Thunder Pulse', 'vot-mizuno-thunder-pulse', 'Vợt ổn định khung cho người mới lên trung cấp', 'Sản phẩm demo với khung ổn định và cảm giác trung tính.', '{"material": "Graphite", "balance": "Even", "shaft_stiffness": "Medium", "recommended_tension_lbs": "18-24", "player_level": "Beginner-Intermediate", "play_style": "Control"}'::jsonb, 'vot mizuno thunder pulse', 'active', false, '2026-06-04T00:00:00Z'),
  ('30000000-0000-4000-8000-000000000005', '10000000-0000-4000-8000-000000000001', '20000000-0000-4000-8000-000000000005', 'Vợt cầu lông Kumpoo Speed Light 5', 'vot-kumpoo-speed-light-5', 'Vợt siêu nhẹ hỗ trợ chuyển cánh tay nhanh', 'Sản phẩm demo phân khúc nhẹ cho phòng tập.', '{"material": "Carbon", "balance": "Head Light", "shaft_stiffness": "Flexible", "recommended_tension_lbs": "18-24", "player_level": "Beginner", "play_style": "Defense"}'::jsonb, 'vot kumpoo speed light 5', 'active', false, '2026-06-05T00:00:00Z'),
  ('30000000-0000-4000-8000-000000000006', '10000000-0000-4000-8000-000000000001', '20000000-0000-4000-8000-000000000006', 'Vợt cầu lông Apacs Force Pro 99', 'vot-apacs-force-pro-99', 'Bản nháp đang hoàn thiện thông số', 'Sản phẩm draft — chưa công bố bán.', '{"material": "Graphite", "balance": "Head Heavy", "shaft_stiffness": "Stiff", "recommended_tension_lbs": "22-28", "player_level": "Advanced", "play_style": "Attack"}'::jsonb, 'vot apacs force pro 99 draft', 'draft', false, null),
  ('30000000-0000-4000-8000-000000000007', '10000000-0000-4000-8000-000000000002', '20000000-0000-4000-8000-000000000004', 'Giày cầu lông Mizuno Court Flex Pro', 'giay-mizuno-court-flex-pro', 'Giày đệm êm cho sân trong nhà', 'Sản phẩm demo giày cầu lông đế chống trượt trong nhà.', '{"upper_material": "Synthetic Mesh", "sole_material": "Non-marking Rubber", "court_type": "Indoor", "player_level": "All levels"}'::jsonb, 'giay mizuno court flex pro', 'active', true, '2026-06-06T00:00:00Z'),
  ('30000000-0000-4000-8000-000000000008', '10000000-0000-4000-8000-000000000002', '20000000-0000-4000-8000-000000000001', 'Giày cầu lông Yonex Court Glide', 'giay-yonex-court-glide', 'Giày nhẹ hỗ trợ đổi hướng nhanh', 'Sản phẩm demo tập trung độ ôm chân và độ bám.', '{"upper_material": "Mesh", "sole_material": "Gum Rubber", "court_type": "Indoor", "player_level": "Intermediate"}'::jsonb, 'giay yonex court glide', 'active', false, '2026-06-07T00:00:00Z'),
  ('30000000-0000-4000-8000-000000000009', '10000000-0000-4000-8000-000000000002', '20000000-0000-4000-8000-000000000003', 'Giày cầu lông Li-Ning Swift Step', 'giay-li-ning-swift-step', 'Mẫu ngừng trưng bày tạm thời', 'Sản phẩm inactive phục vụ kiểm thử catalog.', '{"upper_material": "Synthetic", "sole_material": "Rubber", "court_type": "Indoor", "player_level": "Beginner"}'::jsonb, 'giay li-ning swift step', 'inactive', false, '2026-05-01T00:00:00Z'),
  ('30000000-0000-4000-8000-000000000010', '10000000-0000-4000-8000-000000000003', '20000000-0000-4000-8000-000000000001', 'Cầu lông thi đấu Feather Pro 12 quả', 'cau-feather-pro-12', 'Ống 12 quả tốc độ 77 dùng thi đấu nghiệp dư', 'Sản phẩm demo cầu lông bán theo ống.', '{"material": "Goose Feather", "speed": "77", "quantity_per_tube": 12, "usage": "Training and competition"}'::jsonb, 'cau long feather pro 12', 'active', true, '2026-06-08T00:00:00Z'),
  ('30000000-0000-4000-8000-000000000011', '10000000-0000-4000-8000-000000000003', '20000000-0000-4000-8000-000000000008', 'Cầu lông luyện tập Club Tube 12', 'cau-club-tube-12', 'Ống cầu luyện tập bền cho phòng tập', 'Sản phẩm demo cầu luyện tập giá hợp lý.', '{"material": "Duck Feather", "speed": "76", "quantity_per_tube": 12, "usage": "Training"}'::jsonb, 'cau long club tube 12', 'active', false, '2026-06-09T00:00:00Z'),
  ('30000000-0000-4000-8000-000000000012', '10000000-0000-4000-8000-000000000004', '20000000-0000-4000-8000-000000000002', 'Cước đan vợt Control Spin 0.66 mm', 'cuoc-control-spin-066', 'Dây cảm giác xoáy và kiểm soát', 'Sản phẩm demo dây đan nhiều màu.', '{"gauge_mm": 0.66, "feel": "Medium", "durability": "Medium", "control": "High"}'::jsonb, 'cuoc control spin 0.66', 'active', false, '2026-06-10T00:00:00Z'),
  ('30000000-0000-4000-8000-000000000013', '10000000-0000-4000-8000-000000000004', '20000000-0000-4000-8000-000000000001', 'Cước đan vợt Power Smash 0.68', 'cuoc-power-smash-068', 'Dây thiên lực cho lối đánh smash', 'Sản phẩm demo dây đan độ bền trung bình.', '{"gauge_mm": 0.68, "feel": "Firm", "durability": "High", "control": "Medium"}'::jsonb, 'cuoc power smash 0.68', 'active', false, '2026-06-11T00:00:00Z'),
  ('30000000-0000-4000-8000-000000000014', '10000000-0000-4000-8000-000000000004', '20000000-0000-4000-8000-000000000008', 'Cước đan vợt Soft Feel 0.70', 'cuoc-soft-feel-070', 'Bản draft đang hiệu chỉnh thông số', 'Sản phẩm draft chưa mở bán.', '{"gauge_mm": 0.7, "feel": "Soft", "durability": "Medium", "control": "Medium"}'::jsonb, 'cuoc soft feel 0.70 draft', 'draft', false, null),
  ('30000000-0000-4000-8000-000000000015', '10000000-0000-4000-8000-000000000005', '20000000-0000-4000-8000-000000000008', 'Quấn cán Comfort Dry Pack', 'quan-can-comfort-dry-pack', 'Quấn cán thấm hút bán lẻ và theo pack', 'Sản phẩm demo grip Comfort Dry.', '{"material": "PU", "absorbency": "High", "thickness_mm": 0.6}'::jsonb, 'quan can comfort dry', 'active', true, '2026-06-12T00:00:00Z'),
  ('30000000-0000-4000-8000-000000000016', '10000000-0000-4000-8000-000000000005', '20000000-0000-4000-8000-000000000007', 'Quấn cán Towel Grip Classic', 'quan-can-towel-grip-classic', 'Grip khăn thấm mồ hôi tốt', 'Sản phẩm demo towel grip.', '{"material": "Towel", "absorbency": "Very High", "thickness_mm": 1.2}'::jsonb, 'quan can towel grip', 'active', false, '2026-06-13T00:00:00Z'),
  ('30000000-0000-4000-8000-000000000017', '10000000-0000-4000-8000-000000000005', '20000000-0000-4000-8000-000000000002', 'Quấn cán Pro Overgrip Thin', 'quan-can-pro-overgrip-thin', 'Overgrip mỏng tăng cảm giác cầm', 'Sản phẩm demo overgrip mỏng.', '{"material": "PU Thin", "absorbency": "Medium", "thickness_mm": 0.4}'::jsonb, 'quan can overgrip thin', 'active', false, '2026-06-14T00:00:00Z'),
  ('30000000-0000-4000-8000-000000000018', '10000000-0000-4000-8000-000000000006', '20000000-0000-4000-8000-000000000006', 'Túi vợt Tournament Pro 6 ngăn', 'tui-tournament-pro-6', 'Túi 6 ngăn có ngăn giày riêng', 'Sản phẩm demo túi vợt thi đấu.', '{"capacity_rackets": 6, "has_shoe_compartment": true, "material": "Polyester"}'::jsonb, 'tui vot tournament pro 6', 'active', false, '2026-06-15T00:00:00Z'),
  ('30000000-0000-4000-8000-000000000019', '10000000-0000-4000-8000-000000000006', '20000000-0000-4000-8000-000000000007', 'Balo cầu lông Court Daypack', 'balo-court-daypack', 'Balo hàng ngày tạm ngưng bán', 'Sản phẩm inactive kiểm thử RLS/catalog.', '{"capacity_rackets": 2, "has_shoe_compartment": false, "material": "Nylon"}'::jsonb, 'balo court daypack', 'inactive', false, '2026-04-01T00:00:00Z'),
  ('30000000-0000-4000-8000-000000000020', '10000000-0000-4000-8000-000000000007', '20000000-0000-4000-8000-000000000003', 'Áo thi đấu Match Jersey Pro', 'ao-match-jersey-pro', 'Áo thi đấu thoáng khí nhiều size', 'Sản phẩm demo áo cầu lông.', '{"fit": "Regular", "fabric": "Polyester Mesh", "breathability": "High"}'::jsonb, 'ao match jersey pro', 'active', false, '2026-06-16T00:00:00Z'),
  ('30000000-0000-4000-8000-000000000021', '10000000-0000-4000-8000-000000000007', '20000000-0000-4000-8000-000000000007', 'Quần short Court Flex', 'quan-short-court-flex', 'Quần short co giãn cho tập luyện', 'Sản phẩm demo quần short.', '{"fit": "Athletic", "fabric": "Stretch Polyester", "pockets": 2}'::jsonb, 'quan short court flex', 'active', false, '2026-06-17T00:00:00Z'),
  ('30000000-0000-4000-8000-000000000022', '10000000-0000-4000-8000-000000000008', '20000000-0000-4000-8000-000000000007', 'Vớ thể thao Court Cushion', 'vo-court-cushion', 'Vớ đệm gót và bàn chân trước', 'Sản phẩm demo vớ thể thao.', '{"cushion": "Medium", "length": "Ankle", "pairs_per_pack": 1}'::jsonb, 'vo court cushion', 'active', false, '2026-06-18T00:00:00Z'),
  ('30000000-0000-4000-8000-000000000023', '10000000-0000-4000-8000-000000000009', '20000000-0000-4000-8000-000000000005', 'Băng hỗ trợ cổ tay Support Band', 'bang-co-tay-support-band', 'Mẫu đã lưu trữ lịch sử', 'Sản phẩm archived — giữ tham chiếu lịch sử.', '{"support_level": "Medium", "side": "Unisex", "material": "Elastic"}'::jsonb, 'bang co tay support band', 'archived', false, '2026-01-15T00:00:00Z'),
  ('30000000-0000-4000-8000-000000000024', '10000000-0000-4000-8000-000000000010', '20000000-0000-4000-8000-000000000008', 'Thang tập chân Footwork Ladder 4m', 'thang-footwork-ladder-4m', 'Thang tập chân dài 4 mét', 'Sản phẩm demo phụ kiện luyện tập chân.', '{"length_m": 4, "rungs": 8, "material": "Nylon webbing"}'::jsonb, 'thang tap chan footwork ladder', 'active', false, '2026-06-19T00:00:00Z')
on conflict (id) do update set
  category_id = excluded.category_id,
  brand_id = excluded.brand_id,
  name = excluded.name,
  slug = excluded.slug,
  short_description = excluded.short_description,
  description = excluded.description,
  specifications = excluded.specifications,
  search_keywords = excluded.search_keywords,
  status = excluded.status,
  is_featured = excluded.is_featured,
  published_at = excluded.published_at,
  updated_at = timezone('utc', now());

-- ========== product_variants ==========
insert into public.product_variants (
  id, product_id, sku, name, color_name, color_hex, racket_weight_class,
  grip_size, shoe_size, clothing_size, unit, price, compare_at_price,
  cost_price, is_default, is_active, sort_order
)
values
  ('40000000-0000-4000-8000-000000000001', '30000000-0000-4000-8000-000000000001', 'RKT-YON-AS88-RED-3U-G5', '3U / G5 Đỏ', 'Đỏ', '#C62828', '3U', 'G5', null, null, 'item', 1890000.00, 2190000.00, 1200000.00, true, true, 1),
  ('40000000-0000-4000-8000-000000000002', '30000000-0000-4000-8000-000000000001', 'RKT-YON-AS88-RED-4U-G5', '4U / G5 Đỏ', 'Đỏ', '#C62828', '4U', 'G5', null, null, 'item', 1890000.00, 2190000.00, 1200000.00, false, true, 2),
  ('40000000-0000-4000-8000-000000000003', '30000000-0000-4000-8000-000000000001', 'RKT-YON-AS88-BLU-4U-G6', '4U / G6 Xanh', 'Xanh dương', '#1565C0', '4U', 'G6', null, null, 'item', 1920000.00, null, 1220000.00, false, true, 3),
  ('40000000-0000-4000-8000-000000000004', '30000000-0000-4000-8000-000000000001', 'RKT-YON-AS88-BLK-4U-G5', '4U / G5 Đen', 'Đen', '#212121', '4U', 'G5', null, null, 'item', 1920000.00, null, 1220000.00, false, true, 4),
  ('40000000-0000-4000-8000-000000000005', '30000000-0000-4000-8000-000000000002', 'RKT-VIC-PCX7-BLK-3U-G5', '3U / G5 Đen', 'Đen', '#212121', '3U', 'G5', null, null, 'item', 2450000.00, 2690000.00, 1500000.00, true, true, 1),
  ('40000000-0000-4000-8000-000000000006', '30000000-0000-4000-8000-000000000002', 'RKT-VIC-PCX7-BLK-4U-G5', '4U / G5 Đen', 'Đen', '#212121', '4U', 'G5', null, null, 'item', 2450000.00, 2690000.00, 1500000.00, false, true, 2),
  ('40000000-0000-4000-8000-000000000007', '30000000-0000-4000-8000-000000000002', 'RKT-VIC-PCX7-ORG-4U-G6', '4U / G6 Cam', 'Cam', '#EF6C00', '4U', 'G6', null, null, 'item', 2490000.00, null, 1520000.00, false, true, 3),
  ('40000000-0000-4000-8000-000000000008', '30000000-0000-4000-8000-000000000002', 'RKT-VIC-PCX7-WHT-3U-G5', '3U / G5 Trắng', 'Trắng', '#FAFAFA', '3U', 'G5', null, null, 'item', 2490000.00, null, 1520000.00, false, true, 4),
  ('40000000-0000-4000-8000-000000000009', '30000000-0000-4000-8000-000000000003', 'RKT-LIN-WB900-BLU-4U-G5', '4U / G5 Xanh', 'Xanh dương', '#1E88E5', '4U', 'G5', null, null, 'item', 1650000.00, null, 980000.00, true, true, 1),
  ('40000000-0000-4000-8000-000000000010', '30000000-0000-4000-8000-000000000003', 'RKT-LIN-WB900-BLU-4U-G6', '4U / G6 Xanh', 'Xanh dương', '#1E88E5', '4U', 'G6', null, null, 'item', 1650000.00, null, 980000.00, false, true, 2),
  ('40000000-0000-4000-8000-000000000011', '30000000-0000-4000-8000-000000000003', 'RKT-LIN-WB900-GRN-5U-G5', '5U / G5 Xanh lá', 'Xanh lá', '#2E7D32', '5U', 'G5', null, null, 'item', 1590000.00, null, 950000.00, false, true, 3),
  ('40000000-0000-4000-8000-000000000012', '30000000-0000-4000-8000-000000000004', 'RKT-MIZ-TP-GRY-3U-G5', '3U / G5 Xám', 'Xám', '#757575', '3U', 'G5', null, null, 'item', 1290000.00, null, 780000.00, true, true, 1),
  ('40000000-0000-4000-8000-000000000013', '30000000-0000-4000-8000-000000000004', 'RKT-MIZ-TP-GRY-4U-G5', '4U / G5 Xám', 'Xám', '#757575', '4U', 'G5', null, null, 'item', 1290000.00, null, 780000.00, false, true, 2),
  ('40000000-0000-4000-8000-000000000014', '30000000-0000-4000-8000-000000000004', 'RKT-MIZ-TP-BLU-4U-G6', '4U / G6 Xanh', 'Xanh dương', '#1976D2', '4U', 'G6', null, null, 'item', 1320000.00, null, 800000.00, false, true, 3),
  ('40000000-0000-4000-8000-000000000015', '30000000-0000-4000-8000-000000000005', 'RKT-KUM-SL5-YEL-5U-G5', '5U / G5 Vàng', 'Vàng', '#F9A825', '5U', 'G5', null, null, 'item', 890000.00, null, 520000.00, true, true, 1),
  ('40000000-0000-4000-8000-000000000016', '30000000-0000-4000-8000-000000000005', 'RKT-KUM-SL5-YEL-4U-G5', '4U / G5 Vàng', 'Vàng', '#F9A825', '4U', 'G5', null, null, 'item', 920000.00, null, 540000.00, false, true, 2),
  ('40000000-0000-4000-8000-000000000017', '30000000-0000-4000-8000-000000000006', 'RKT-APA-FP99-BLK-4U-G5', '4U / G5 Đen (draft)', 'Đen', '#000000', '4U', 'G5', null, null, 'item', 2100000.00, null, 1300000.00, true, false, 1),
  ('40000000-0000-4000-8000-000000000018', '30000000-0000-4000-8000-000000000007', 'SHO-MIZ-CFP-WHT-39', 'Size 39', 'Trắng', '#FAFAFA', null, null, '39', null, 'item', 1590000.00, null, 900000.00, false, true, 1),
  ('40000000-0000-4000-8000-000000000019', '30000000-0000-4000-8000-000000000007', 'SHO-MIZ-CFP-WHT-40', 'Size 40', 'Trắng', '#FAFAFA', null, null, '40', null, 'item', 1590000.00, null, 900000.00, false, true, 2),
  ('40000000-0000-4000-8000-000000000020', '30000000-0000-4000-8000-000000000007', 'SHO-MIZ-CFP-WHT-41', 'Size 41', 'Trắng', '#FAFAFA', null, null, '41', null, 'item', 1590000.00, null, 900000.00, true, true, 3),
  ('40000000-0000-4000-8000-000000000021', '30000000-0000-4000-8000-000000000007', 'SHO-MIZ-CFP-WHT-42', 'Size 42', 'Trắng', '#FAFAFA', null, null, '42', null, 'item', 1590000.00, null, 900000.00, false, true, 4),
  ('40000000-0000-4000-8000-000000000022', '30000000-0000-4000-8000-000000000007', 'SHO-MIZ-CFP-WHT-43', 'Size 43', 'Trắng', '#FAFAFA', null, null, '43', null, 'item', 1590000.00, null, 900000.00, false, true, 5),
  ('40000000-0000-4000-8000-000000000023', '30000000-0000-4000-8000-000000000008', 'SHO-YON-CG-BLK-39', 'Size 39', 'Đen', '#212121', null, null, '39', null, 'item', 1450000.00, null, 820000.00, false, true, 1),
  ('40000000-0000-4000-8000-000000000024', '30000000-0000-4000-8000-000000000008', 'SHO-YON-CG-BLK-40', 'Size 40', 'Đen', '#212121', null, null, '40', null, 'item', 1450000.00, null, 820000.00, false, true, 2),
  ('40000000-0000-4000-8000-000000000025', '30000000-0000-4000-8000-000000000008', 'SHO-YON-CG-BLK-41', 'Size 41', 'Đen', '#212121', null, null, '41', null, 'item', 1450000.00, null, 820000.00, false, true, 3),
  ('40000000-0000-4000-8000-000000000026', '30000000-0000-4000-8000-000000000008', 'SHO-YON-CG-BLK-42', 'Size 42', 'Đen', '#212121', null, null, '42', null, 'item', 1450000.00, null, 820000.00, true, true, 4),
  ('40000000-0000-4000-8000-000000000027', '30000000-0000-4000-8000-000000000008', 'SHO-YON-CG-BLK-43', 'Size 43', 'Đen', '#212121', null, null, '43', null, 'item', 1450000.00, null, 820000.00, false, true, 5),
  ('40000000-0000-4000-8000-000000000028', '30000000-0000-4000-8000-000000000009', 'SHO-LIN-SS-GRY-40', 'Size 40', 'Xám', '#9E9E9E', null, null, '40', null, 'item', 990000.00, 1190000.00, 550000.00, false, false, 1),
  ('40000000-0000-4000-8000-000000000029', '30000000-0000-4000-8000-000000000009', 'SHO-LIN-SS-GRY-41', 'Size 41', 'Xám', '#9E9E9E', null, null, '41', null, 'item', 990000.00, 1190000.00, 550000.00, true, false, 2),
  ('40000000-0000-4000-8000-000000000030', '30000000-0000-4000-8000-000000000009', 'SHO-LIN-SS-GRY-42', 'Size 42', 'Xám', '#9E9E9E', null, null, '42', null, 'item', 990000.00, 1190000.00, 550000.00, false, false, 3),
  ('40000000-0000-4000-8000-000000000031', '30000000-0000-4000-8000-000000000010', 'SHT-YON-FP-TUBE12', 'Ống 12 quả', null, null, null, null, null, null, 'tube', 520000.00, null, 320000.00, true, true, 1),
  ('40000000-0000-4000-8000-000000000032', '30000000-0000-4000-8000-000000000011', 'SHT-PRO-CLUB-TUBE12', 'Ống 12 quả', null, null, null, null, null, null, 'tube', 280000.00, null, 160000.00, true, true, 1),
  ('40000000-0000-4000-8000-000000000033', '30000000-0000-4000-8000-000000000012', 'STR-CTL-066-WHT', 'Trắng', 'Trắng', '#FFFFFF', null, null, null, null, 'set', 180000.00, null, 90000.00, true, true, 1),
  ('40000000-0000-4000-8000-000000000034', '30000000-0000-4000-8000-000000000012', 'STR-CTL-066-BLK', 'Đen', 'Đen', '#000000', null, null, null, null, 'set', 180000.00, null, 90000.00, false, true, 2),
  ('40000000-0000-4000-8000-000000000035', '30000000-0000-4000-8000-000000000012', 'STR-CTL-066-YEL', 'Vàng', 'Vàng', '#F9A825', null, null, null, null, 'set', 180000.00, null, 90000.00, false, true, 3),
  ('40000000-0000-4000-8000-000000000036', '30000000-0000-4000-8000-000000000012', 'STR-CTL-066-BLU', 'Xanh dương', 'Xanh dương', '#1E88E5', null, null, null, null, 'set', 180000.00, null, 90000.00, false, true, 4),
  ('40000000-0000-4000-8000-000000000037', '30000000-0000-4000-8000-000000000012', 'STR-CTL-066-RED', 'Đỏ', 'Đỏ', '#E53935', null, null, null, null, 'set', 180000.00, null, 90000.00, false, true, 5),
  ('40000000-0000-4000-8000-000000000038', '30000000-0000-4000-8000-000000000013', 'STR-PWR-068-WHT', 'Trắng', 'Trắng', '#FFFFFF', null, null, null, null, 'set', 220000.00, null, 110000.00, false, true, 1),
  ('40000000-0000-4000-8000-000000000039', '30000000-0000-4000-8000-000000000013', 'STR-PWR-068-BLK', 'Đen', 'Đen', '#000000', null, null, null, null, 'set', 220000.00, null, 110000.00, true, true, 2),
  ('40000000-0000-4000-8000-000000000040', '30000000-0000-4000-8000-000000000013', 'STR-PWR-068-RED', 'Đỏ', 'Đỏ', '#C62828', null, null, null, null, 'set', 220000.00, null, 110000.00, false, true, 3),
  ('40000000-0000-4000-8000-000000000041', '30000000-0000-4000-8000-000000000014', 'STR-SFT-070-WHT', 'Trắng (draft)', 'Trắng', '#FFFFFF', null, null, null, null, 'set', 150000.00, null, 70000.00, true, false, 1),
  ('40000000-0000-4000-8000-000000000042', '30000000-0000-4000-8000-000000000015', 'GRP-COM-DRY-BLK-1', '1 cuốn', 'Đen', '#000000', null, null, null, null, 'item', 35000.00, null, 15000.00, true, true, 1),
  ('40000000-0000-4000-8000-000000000043', '30000000-0000-4000-8000-000000000015', 'GRP-COM-DRY-BLK-P3', 'Pack 3 cuốn', 'Đen', '#000000', null, null, null, null, 'pack', 99000.00, 105000.00, 40000.00, false, true, 2),
  ('40000000-0000-4000-8000-000000000044', '30000000-0000-4000-8000-000000000015', 'GRP-COM-DRY-BLK-P5', 'Pack 5 cuốn', 'Đen', '#000000', null, null, null, null, 'pack', 155000.00, 175000.00, 65000.00, false, true, 3),
  ('40000000-0000-4000-8000-000000000045', '30000000-0000-4000-8000-000000000016', 'GRP-TWL-CLS-WHT-1', '1 cuốn Trắng', 'Trắng', '#FFFFFF', null, null, null, null, 'item', 45000.00, null, 20000.00, true, true, 1),
  ('40000000-0000-4000-8000-000000000046', '30000000-0000-4000-8000-000000000016', 'GRP-TWL-CLS-BLU-1', '1 cuốn Xanh', 'Xanh dương', '#1565C0', null, null, null, null, 'item', 45000.00, null, 20000.00, false, true, 2),
  ('40000000-0000-4000-8000-000000000047', '30000000-0000-4000-8000-000000000017', 'GRP-PRO-OVG-BLK-1', '1 cuốn', 'Đen', '#000000', null, null, null, null, 'item', 39000.00, null, 18000.00, true, true, 1),
  ('40000000-0000-4000-8000-000000000048', '30000000-0000-4000-8000-000000000017', 'GRP-PRO-OVG-RED-P3', 'Pack 3 cuốn', 'Đỏ', '#E53935', null, null, null, null, 'pack', 110000.00, null, 50000.00, false, true, 2),
  ('40000000-0000-4000-8000-000000000049', '30000000-0000-4000-8000-000000000018', 'BAG-APA-TP6-BLK', 'Đen', 'Đen', '#212121', null, null, null, null, 'item', 1290000.00, null, 700000.00, true, true, 1),
  ('40000000-0000-4000-8000-000000000050', '30000000-0000-4000-8000-000000000018', 'BAG-APA-TP6-BLU', 'Xanh dương', 'Xanh dương', '#1565C0', null, null, null, null, 'item', 1320000.00, null, 720000.00, false, true, 2),
  ('40000000-0000-4000-8000-000000000051', '30000000-0000-4000-8000-000000000019', 'BAG-KAM-CDP-GRY', 'Xám', 'Xám', '#9E9E9E', null, null, null, null, 'item', 690000.00, null, 380000.00, true, false, 1),
  ('40000000-0000-4000-8000-000000000052', '30000000-0000-4000-8000-000000000020', 'CLT-LIN-MJP-RED-S', 'Size S', 'Đỏ', '#E53935', null, null, null, 'S', 'item', 390000.00, null, 180000.00, false, true, 1),
  ('40000000-0000-4000-8000-000000000053', '30000000-0000-4000-8000-000000000020', 'CLT-LIN-MJP-RED-M', 'Size M', 'Đỏ', '#E53935', null, null, null, 'M', 'item', 390000.00, null, 180000.00, true, true, 2),
  ('40000000-0000-4000-8000-000000000054', '30000000-0000-4000-8000-000000000020', 'CLT-LIN-MJP-RED-L', 'Size L', 'Đỏ', '#E53935', null, null, null, 'L', 'item', 390000.00, null, 180000.00, false, true, 3),
  ('40000000-0000-4000-8000-000000000055', '30000000-0000-4000-8000-000000000020', 'CLT-LIN-MJP-RED-XL', 'Size XL', 'Đỏ', '#E53935', null, null, null, 'XL', 'item', 390000.00, null, 180000.00, false, true, 4),
  ('40000000-0000-4000-8000-000000000056', '30000000-0000-4000-8000-000000000020', 'CLT-LIN-MJP-RED-XXL', 'Size XXL', 'Đỏ', '#E53935', null, null, null, 'XXL', 'item', 390000.00, null, 180000.00, false, true, 5),
  ('40000000-0000-4000-8000-000000000057', '30000000-0000-4000-8000-000000000021', 'CLT-KAM-CSF-NVY-S', 'Size S', 'Navy', '#0D47A1', null, null, null, 'S', 'item', 320000.00, null, 150000.00, false, true, 1),
  ('40000000-0000-4000-8000-000000000058', '30000000-0000-4000-8000-000000000021', 'CLT-KAM-CSF-NVY-M', 'Size M', 'Navy', '#0D47A1', null, null, null, 'M', 'item', 320000.00, null, 150000.00, false, true, 2),
  ('40000000-0000-4000-8000-000000000059', '30000000-0000-4000-8000-000000000021', 'CLT-KAM-CSF-NVY-L', 'Size L', 'Navy', '#0D47A1', null, null, null, 'L', 'item', 320000.00, null, 150000.00, true, true, 3),
  ('40000000-0000-4000-8000-000000000060', '30000000-0000-4000-8000-000000000021', 'CLT-KAM-CSF-NVY-XL', 'Size XL', 'Navy', '#0D47A1', null, null, null, 'XL', 'item', 320000.00, null, 150000.00, false, true, 4),
  ('40000000-0000-4000-8000-000000000061', '30000000-0000-4000-8000-000000000022', 'SOK-KAM-CC-WHT-FREE', 'Free size', 'Trắng', '#FFFFFF', null, null, null, null, 'pair', 89000.00, null, 35000.00, true, true, 1),
  ('40000000-0000-4000-8000-000000000062', '30000000-0000-4000-8000-000000000023', 'PRT-KUM-SB-BLK-ONE', 'One size', 'Đen', '#000000', null, null, null, null, 'item', 120000.00, null, 50000.00, true, false, 1),
  ('40000000-0000-4000-8000-000000000063', '30000000-0000-4000-8000-000000000024', 'TRN-PRO-FL-4M', '4 mét', null, null, null, null, null, null, 'item', 250000.00, null, 120000.00, true, true, 1)
on conflict (id) do update set
  product_id = excluded.product_id,
  sku = excluded.sku,
  name = excluded.name,
  color_name = excluded.color_name,
  color_hex = excluded.color_hex,
  racket_weight_class = excluded.racket_weight_class,
  grip_size = excluded.grip_size,
  shoe_size = excluded.shoe_size,
  clothing_size = excluded.clothing_size,
  unit = excluded.unit,
  price = excluded.price,
  compare_at_price = excluded.compare_at_price,
  cost_price = excluded.cost_price,
  is_default = excluded.is_default,
  is_active = excluded.is_active,
  sort_order = excluded.sort_order,
  updated_at = timezone('utc', now());

-- ========== product_images ==========
insert into public.product_images (id, product_id, variant_id, storage_path, alt_text, sort_order, is_primary)
values
  ('50000000-0000-4000-8000-000000000001', '30000000-0000-4000-8000-000000000001', null, 'product-images/30000000-0000-4000-8000-000000000001/main.webp', 'Ảnh chính Vợt cầu lông Yonex Aero Strike 88', 0, true),
  ('50000000-0000-4000-8000-000000000002', '30000000-0000-4000-8000-000000000001', null, 'product-images/30000000-0000-4000-8000-000000000001/gallery-01.webp', 'Ảnh phụ Vợt cầu lông Yonex Aero Strike 88', 1, false),
  ('50000000-0000-4000-8000-000000000003', '30000000-0000-4000-8000-000000000002', null, 'product-images/30000000-0000-4000-8000-000000000002/main.webp', 'Ảnh chính Vợt cầu lông Victor Power Core X7', 0, true),
  ('50000000-0000-4000-8000-000000000004', '30000000-0000-4000-8000-000000000002', null, 'product-images/30000000-0000-4000-8000-000000000002/gallery-01.webp', 'Ảnh phụ Vợt cầu lông Victor Power Core X7', 1, false),
  ('50000000-0000-4000-8000-000000000005', '30000000-0000-4000-8000-000000000003', null, 'product-images/30000000-0000-4000-8000-000000000003/main.webp', 'Ảnh chính Vợt cầu lông Li-Ning Wind Blade 900', 0, true),
  ('50000000-0000-4000-8000-000000000006', '30000000-0000-4000-8000-000000000003', null, 'product-images/30000000-0000-4000-8000-000000000003/gallery-01.webp', 'Ảnh phụ Vợt cầu lông Li-Ning Wind Blade 900', 1, false),
  ('50000000-0000-4000-8000-000000000007', '30000000-0000-4000-8000-000000000004', null, 'product-images/30000000-0000-4000-8000-000000000004/main.webp', 'Ảnh chính Vợt cầu lông Mizuno Thunder Pulse', 0, true),
  ('50000000-0000-4000-8000-000000000008', '30000000-0000-4000-8000-000000000005', null, 'product-images/30000000-0000-4000-8000-000000000005/main.webp', 'Ảnh chính Vợt cầu lông Kumpoo Speed Light 5', 0, true),
  ('50000000-0000-4000-8000-000000000009', '30000000-0000-4000-8000-000000000006', null, 'product-images/30000000-0000-4000-8000-000000000006/main.webp', 'Ảnh chính Vợt cầu lông Apacs Force Pro 99', 0, true),
  ('50000000-0000-4000-8000-000000000010', '30000000-0000-4000-8000-000000000007', null, 'product-images/30000000-0000-4000-8000-000000000007/main.webp', 'Ảnh chính Giày cầu lông Mizuno Court Flex Pro', 0, true),
  ('50000000-0000-4000-8000-000000000011', '30000000-0000-4000-8000-000000000007', null, 'product-images/30000000-0000-4000-8000-000000000007/gallery-01.webp', 'Ảnh phụ Giày cầu lông Mizuno Court Flex Pro', 1, false),
  ('50000000-0000-4000-8000-000000000012', '30000000-0000-4000-8000-000000000008', null, 'product-images/30000000-0000-4000-8000-000000000008/main.webp', 'Ảnh chính Giày cầu lông Yonex Court Glide', 0, true),
  ('50000000-0000-4000-8000-000000000013', '30000000-0000-4000-8000-000000000009', null, 'product-images/30000000-0000-4000-8000-000000000009/main.webp', 'Ảnh chính Giày cầu lông Li-Ning Swift Step', 0, true),
  ('50000000-0000-4000-8000-000000000014', '30000000-0000-4000-8000-000000000010', null, 'product-images/30000000-0000-4000-8000-000000000010/main.webp', 'Ảnh chính Cầu lông thi đấu Feather Pro 12 quả', 0, true),
  ('50000000-0000-4000-8000-000000000015', '30000000-0000-4000-8000-000000000010', null, 'product-images/30000000-0000-4000-8000-000000000010/gallery-01.webp', 'Ảnh phụ Cầu lông thi đấu Feather Pro 12 quả', 1, false),
  ('50000000-0000-4000-8000-000000000016', '30000000-0000-4000-8000-000000000011', null, 'product-images/30000000-0000-4000-8000-000000000011/main.webp', 'Ảnh chính Cầu lông luyện tập Club Tube 12', 0, true),
  ('50000000-0000-4000-8000-000000000017', '30000000-0000-4000-8000-000000000012', null, 'product-images/30000000-0000-4000-8000-000000000012/main.webp', 'Ảnh chính Cước đan vợt Control Spin 0.66 mm', 0, true),
  ('50000000-0000-4000-8000-000000000018', '30000000-0000-4000-8000-000000000013', null, 'product-images/30000000-0000-4000-8000-000000000013/main.webp', 'Ảnh chính Cước đan vợt Power Smash 0.68', 0, true),
  ('50000000-0000-4000-8000-000000000019', '30000000-0000-4000-8000-000000000014', null, 'product-images/30000000-0000-4000-8000-000000000014/main.webp', 'Ảnh chính Cước đan vợt Soft Feel 0.70', 0, true),
  ('50000000-0000-4000-8000-000000000020', '30000000-0000-4000-8000-000000000015', null, 'product-images/30000000-0000-4000-8000-000000000015/main.webp', 'Ảnh chính Quấn cán Comfort Dry Pack', 0, true),
  ('50000000-0000-4000-8000-000000000021', '30000000-0000-4000-8000-000000000015', null, 'product-images/30000000-0000-4000-8000-000000000015/gallery-01.webp', 'Ảnh phụ Quấn cán Comfort Dry Pack', 1, false),
  ('50000000-0000-4000-8000-000000000022', '30000000-0000-4000-8000-000000000016', null, 'product-images/30000000-0000-4000-8000-000000000016/main.webp', 'Ảnh chính Quấn cán Towel Grip Classic', 0, true),
  ('50000000-0000-4000-8000-000000000023', '30000000-0000-4000-8000-000000000017', null, 'product-images/30000000-0000-4000-8000-000000000017/main.webp', 'Ảnh chính Quấn cán Pro Overgrip Thin', 0, true),
  ('50000000-0000-4000-8000-000000000024', '30000000-0000-4000-8000-000000000018', null, 'product-images/30000000-0000-4000-8000-000000000018/main.webp', 'Ảnh chính Túi vợt Tournament Pro 6 ngăn', 0, true),
  ('50000000-0000-4000-8000-000000000025', '30000000-0000-4000-8000-000000000019', null, 'product-images/30000000-0000-4000-8000-000000000019/main.webp', 'Ảnh chính Balo cầu lông Court Daypack', 0, true),
  ('50000000-0000-4000-8000-000000000026', '30000000-0000-4000-8000-000000000020', null, 'product-images/30000000-0000-4000-8000-000000000020/main.webp', 'Ảnh chính Áo thi đấu Match Jersey Pro', 0, true),
  ('50000000-0000-4000-8000-000000000027', '30000000-0000-4000-8000-000000000021', null, 'product-images/30000000-0000-4000-8000-000000000021/main.webp', 'Ảnh chính Quần short Court Flex', 0, true),
  ('50000000-0000-4000-8000-000000000028', '30000000-0000-4000-8000-000000000022', null, 'product-images/30000000-0000-4000-8000-000000000022/main.webp', 'Ảnh chính Vớ thể thao Court Cushion', 0, true),
  ('50000000-0000-4000-8000-000000000029', '30000000-0000-4000-8000-000000000023', null, 'product-images/30000000-0000-4000-8000-000000000023/main.webp', 'Ảnh chính Băng hỗ trợ cổ tay Support Band', 0, true),
  ('50000000-0000-4000-8000-000000000030', '30000000-0000-4000-8000-000000000024', null, 'product-images/30000000-0000-4000-8000-000000000024/main.webp', 'Ảnh chính Thang tập chân Footwork Ladder 4m', 0, true),
  ('50000000-0000-4000-8000-000000000031', '30000000-0000-4000-8000-000000000001', '40000000-0000-4000-8000-000000000003', 'product-images/30000000-0000-4000-8000-000000000001/rkt-yon-as88-blu-4u-g6.webp', 'Ảnh biến thể 4U / G6 Xanh', 0, true),
  ('50000000-0000-4000-8000-000000000032', '30000000-0000-4000-8000-000000000002', '40000000-0000-4000-8000-000000000007', 'product-images/30000000-0000-4000-8000-000000000002/rkt-vic-pcx7-org-4u-g6.webp', 'Ảnh biến thể 4U / G6 Cam', 0, true)
on conflict (id) do update set
  product_id = excluded.product_id,
  variant_id = excluded.variant_id,
  storage_path = excluded.storage_path,
  alt_text = excluded.alt_text,
  sort_order = excluded.sort_order,
  is_primary = excluded.is_primary,
  updated_at = timezone('utc', now());

-- ========== inventory ==========
insert into public.inventory (variant_id, quantity_on_hand, quantity_reserved, reorder_level, allow_backorder)
values
  ('40000000-0000-4000-8000-000000000001', 45, 2, 8, false),
  ('40000000-0000-4000-8000-000000000002', 7, 0, 5, false),
  ('40000000-0000-4000-8000-000000000003', 3, 1, 5, false),
  ('40000000-0000-4000-8000-000000000004', 0, 0, 5, false),
  ('40000000-0000-4000-8000-000000000005', 45, 2, 8, false),
  ('40000000-0000-4000-8000-000000000006', 11, 0, 5, false),
  ('40000000-0000-4000-8000-000000000007', 2, 0, 5, false),
  ('40000000-0000-4000-8000-000000000008', 13, 0, 5, false),
  ('40000000-0000-4000-8000-000000000009', 45, 2, 8, false),
  ('40000000-0000-4000-8000-000000000010', 15, 0, 5, false),
  ('40000000-0000-4000-8000-000000000011', 16, 0, 5, false),
  ('40000000-0000-4000-8000-000000000012', 17, 0, 5, false),
  ('40000000-0000-4000-8000-000000000013', 18, 0, 5, false),
  ('40000000-0000-4000-8000-000000000014', 19, 1, 5, false),
  ('40000000-0000-4000-8000-000000000015', 20, 0, 5, false),
  ('40000000-0000-4000-8000-000000000016', 21, 0, 5, false),
  ('40000000-0000-4000-8000-000000000017', 0, 0, 0, false),
  ('40000000-0000-4000-8000-000000000018', 4, 1, 5, false),
  ('40000000-0000-4000-8000-000000000019', 24, 0, 5, false),
  ('40000000-0000-4000-8000-000000000020', 25, 0, 5, false),
  ('40000000-0000-4000-8000-000000000021', 5, 0, 5, false),
  ('40000000-0000-4000-8000-000000000022', 6, 0, 5, false),
  ('40000000-0000-4000-8000-000000000023', 0, 0, 5, false),
  ('40000000-0000-4000-8000-000000000024', 8, 0, 5, false),
  ('40000000-0000-4000-8000-000000000025', 9, 0, 5, false),
  ('40000000-0000-4000-8000-000000000026', 10, 0, 5, false),
  ('40000000-0000-4000-8000-000000000027', 11, 0, 5, false),
  ('40000000-0000-4000-8000-000000000028', 0, 0, 0, false),
  ('40000000-0000-4000-8000-000000000029', 0, 0, 0, false),
  ('40000000-0000-4000-8000-000000000030', 0, 0, 0, false),
  ('40000000-0000-4000-8000-000000000031', 15, 0, 5, false),
  ('40000000-0000-4000-8000-000000000032', 16, 0, 5, false),
  ('40000000-0000-4000-8000-000000000033', 17, 0, 5, false),
  ('40000000-0000-4000-8000-000000000034', 18, 0, 5, false),
  ('40000000-0000-4000-8000-000000000035', 2, 0, 5, false),
  ('40000000-0000-4000-8000-000000000036', 20, 0, 5, false),
  ('40000000-0000-4000-8000-000000000037', 0, 0, 5, false),
  ('40000000-0000-4000-8000-000000000038', 22, 0, 5, false),
  ('40000000-0000-4000-8000-000000000039', 23, 0, 5, false),
  ('40000000-0000-4000-8000-000000000040', 24, 0, 5, false),
  ('40000000-0000-4000-8000-000000000041', 0, 0, 0, false),
  ('40000000-0000-4000-8000-000000000042', 3, 0, 10, false),
  ('40000000-0000-4000-8000-000000000043', 6, 0, 5, false),
  ('40000000-0000-4000-8000-000000000044', 7, 0, 5, false),
  ('40000000-0000-4000-8000-000000000045', 8, 0, 5, false),
  ('40000000-0000-4000-8000-000000000046', 9, 0, 5, false),
  ('40000000-0000-4000-8000-000000000047', 10, 0, 5, false),
  ('40000000-0000-4000-8000-000000000048', 11, 0, 5, false),
  ('40000000-0000-4000-8000-000000000049', 12, 1, 5, false),
  ('40000000-0000-4000-8000-000000000050', 0, 0, 3, true),
  ('40000000-0000-4000-8000-000000000051', 0, 0, 0, false),
  ('40000000-0000-4000-8000-000000000052', 15, 0, 5, false),
  ('40000000-0000-4000-8000-000000000053', 16, 0, 5, false),
  ('40000000-0000-4000-8000-000000000054', 17, 0, 5, false),
  ('40000000-0000-4000-8000-000000000055', 18, 0, 5, false),
  ('40000000-0000-4000-8000-000000000056', 0, 0, 5, false),
  ('40000000-0000-4000-8000-000000000057', 20, 0, 5, false),
  ('40000000-0000-4000-8000-000000000058', 21, 0, 5, false),
  ('40000000-0000-4000-8000-000000000059', 22, 0, 5, false),
  ('40000000-0000-4000-8000-000000000060', 23, 0, 5, false),
  ('40000000-0000-4000-8000-000000000061', 24, 0, 5, false),
  ('40000000-0000-4000-8000-000000000062', 0, 0, 0, false),
  ('40000000-0000-4000-8000-000000000063', 5, 0, 5, false)
on conflict (variant_id) do update set
  quantity_on_hand = excluded.quantity_on_hand,
  quantity_reserved = excluded.quantity_reserved,
  reorder_level = excluded.reorder_level,
  allow_backorder = excluded.allow_backorder,
  updated_at = timezone('utc', now());

commit;

-- Counts: categories=10 brands=8 products=24 variants=63 images=32 inventory=63
-- Product status: {'active': 19, 'draft': 2, 'inactive': 2, 'archived': 1}
-- Featured active: 6
